#!/bin/sh
realeaseNo=`cat /etc/redhat-release |sed -rn 's/.*([[:digit:]]+)\..*\..*/\1/p'`
PXEinstall (){
setenforce 0
systemctl stop firewalld
rpm -q net-tools ||yum -y install net-tools
ifconfig |grep eth0
if [ "$?" -ne "0" ];then
	echo "请将网卡更名为eth0;才能继续运行本脚本；更改过程中会强制重启；您是否还要继续执行？"
	read -p " 请按y继续YUN行: " ipsure
	[ "${ipsure}" ] == "y" && sed -ir '/GRUB_CMDLINE_LINUX/s/"$/ net.ifnames=0"/p' /etc/default/grub && grub2-mkconfig -o /etc/grub2.cfg &>/dev/null
	read -p "请输入eth0的IP: " ip
	read -p "请输入要设置的子网掩码（prefix）如 24: " prefix
	read -p "请输入要设置的网关： " gateway
	cat >/etc/sysconfig/network-scripts/ifcfg-eth0 <<EOF
DEVICE="eth0"
BOOTPROTO="static"
ONBOOT="yes"
TYPE="Ethernet"
IPADDR=$ip
PREFIX=$prefix
GATEWAY=$gateway
DNS1=114.114.114.114
EOF
	echo "请重启系统；然后重新执行本脚本"
	echo "重启后如果无法联网 请执行service network restart 或者 nmcli con reload; nmcli con up eth0"
	reboot
fi
ipeth0=`ifconfig eth0|sed -rn '/inet\>/s/[^0-9]+([0-9.]+).*/\1/p'`
neteth0=`ifconfig eth0|sed -rn '/inet\>/s/[^0-9]+([0-9.]+).*/\1/p'|cut -d. -f1-3`
route=`ip route|grep default|grep eth0|sed -rn 's/[^0-9]+([0-9.]+).*/\1/p'`
route6=`ip route|grep default|sed -rn 's/[^0-9]+([0-9.]+).*/\1/p'`
srinfo6=`lsblk|awk '/sr/{print $1}'`
srinfo=`lsblk|egrep -o 'sr[^ ]*'`
for scan in /sys/class/scsi_host/host*/scan;do echo "- - -" >$scan;done
if [ "$realeaseNo" -eq "8" ];then            
	dnf -y install dhcp-server tftp-server httpd syslinux-nonlinux 
	systemctl enable --now httpd tftp dhcpd
fi 
if [ "$realeaseNo" -eq "7" ];then            
	yum -y install httpd tftp-server dhcp syslinux 
	systemctl enable --now httpd tftp dhcpd
fi 
if [ "$realeaseNo" -eq "6" ];then            
	yum -y install httpd tftp-server dhcp syslinux 
	service httpd start;service dhcpd restart
	sed -i '/disable/s/yes/no/' /etc/xinetd.d/tftp
	service xinetd restart
fi 
	
	mkdir /var/www/html/centos/{6,7,8}/isos/x86_64/ -pv &>/dev/null

if [ "$realeaseNo" -eq "7" -o "$realeaseNo" -eq "8" ];then
	srinfo6=${srinfo}
fi
	for sr in ${srinfo6};do
		mkdir /mnt/${sr} -p &>/dev/null
		mount /dev/${sr} /mnt/${sr}	
		if [ -d /mnt/${sr}/AppStream ];then
			mount /dev/${sr} /var/www/html/centos/8/isos/x86_64/ &>/dev/null
			mkdir  /var/www/html/ksdir -p &>/dev/null
			mkdir /var/lib/tftpboot/8 &> /dev/null
			\cp -a /mnt/${sr}/isolinux/{vmlinuz,initrd.img} /var/lib/tftpboot/8/

cat >/var/www/html/ksdir/ks8.cfg <<EOF
#version=RHEL8
ignoredisk --only-use=sda
zerombr
text
reboot
# Partition clearing information
clearpart --all --initlabel
selinux --disabled
firewall --disabled

# Use graphical install
#repo --name="Appstream"  --baseurl=http://${ipeth0}/centos/8/isos/x86_64/AppStream
url --url=http://${ipeth0}/centos/8/isos/x86_64/
#repo --name="AppStream" --baseurl=file:///run/install/repo/AppStream
# Use CDROM installation media
# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=dhcp --device=ens160 --ipv6=auto --activate
network  --hostname=centos8.magedu.com
# Root password
# Run the Setup Agent on first boot
rootpw --iscrypted \$1\$jb2QI2x8\$wWAOeOxXerdfYXyVwV0890
firstboot --enable
# Do not configure the X Window System
skipx
# System services
services --disabled="chronyd"
# System timezone
timezone Asia/Shanghai --isUtc --nontp
user --name=wang --password=\$6$oU$fb/02CWfLb5l8f\$sgEZeR7c7DpqfpmFDH6huSmDbW1XQNR4qKl2EPns.gOXqlnAIgv9pTogtFVaDtEpMOC.SWXKYqxfVtd9MCwxb1 --iscrypted --gecos="wang"
# Disk partitioning information
part / --fstype="xfs" --ondisk=sda --size=10000
part /data --fstype="xfs" --ondisk=sda --size=3200
part swap --fstype="swap" --ondisk=sda --size=2048
part /boot --fstype="ext4" --ondisk=sda --size=700

%packages
@^minimal-environment
kexec-tools

%end

%addon com_redhat_kdump --enable --reserve-mb='auto'

%end

%anaconda
pwpolicy root --minlen=6 --minquality=1 --notstrict --nochanges --notempty
pwpolicy user --minlen=6 --minquality=1 --notstrict --nochanges --emptyok
pwpolicy luks --minlen=6 --minquality=1 --notstrict --nochanges --notempty
%end
EOF
		fi
		if [ -e /mnt/${sr}/RPM-GPG-KEY-CentOS-6 ];then
			mount /dev/${sr} /var/www/html/centos/6/isos/x86_64/ &>/dev/null
			mkdir  /var/www/html/ksdir -p &>/dev/null
			mkdir /var/lib/tftpboot/6
			\cp -a /mnt/${sr}/isolinux/{vmlinuz,initrd.img} /var/lib/tftpboot/6/ &>/dev/null
cat >/var/www/html/ksdir/ks6.cfg <<EOF

#ckstart file automatically generated by anaconda.

#version=DEVEL
install
url --url=http://${ipeth0}/centos/6/isos/x86_64/
lang en_US.UTF-8
keyboard us
network --onboot yes --device eth0 --bootproto dhcp --noipv6
rootpw  --iscrypted \$1\$jb2QI2x8\$wWAOeOxXerdfYXyVwV0890
firewall --disabled
authconfig --enableshadow --passalgo=sha512
selinux --disabled
timezone Asia/Shanghai
bootloader --location=mbr --driveorder=sda --append="crashkernel=auto rhgb quiet"
# The following is the partition information you requested
# Note that any partitions you deleted are not expressed
# here so unless you clea:r all partitions first, this is
# not guaranteed to work
clearpart --all
zerombr
reboot
text
part /boot --fstype=ext4 --size=400
part / --fstype=ext4 --size=10000
part /data --fstype=ext4 --size=3000

part swap --size=2048

%packages
@core
autofs
%end

%post
useradd wang
echo magedu | passwd --stdin wang 
%end
EOF
		fi
		if [ -e /mnt/${sr}/RPM-GPG-KEY-CentOS-7 ];then
        	mount /dev/${sr} /var/www/html/centos/7/isos/x86_64/ &>/dev/null
			mkdir  /var/www/html/ksdir -p &>/dev/null
			mkdir /var/lib/tftpboot/7 &>/dev/null
			\cp -a /mnt/${sr}/isolinux/{vmlinuz,initrd.img} /var/lib/tftpboot/7/
cat >/var/www/html/ksdir/ks7.cfg <<EOF
#platform=x86, AMD64, or Intel EM64T
#version=DEVEL
# Install OS instead of upgrade
install
# X Window System configuration information
xconfig  --startxonboot
# Keyboard layouts
# old format: keyboard us
# new format:
keyboard --vckeymap=us --xlayouts='us'
# Root password
rootpw --iscrypted \$1\$jb2QI2x8\$wWAOeOxXerdfYXyVwV0890
# Use network installation
url --url="http://${ipeth0}/centos/7/isos/x86_64"
# System language
lang en_US
# System authorization information
auth  --useshadow  --passalgo=sha512
# Use text mode install
text
# Run the Setup Agent on first boot
firstboot --enable
# SELinux configuration
selinux --disabled
# Do not configure the X Window System
skipx

# System services
services --disabled="chronyd"
ignoredisk --only-use=sda
# Firewall configuration
firewall --disabled
# Network information
network  --bootproto=dhcp --device=ens33
# Reboot after installation
reboot
# System timezone
timezone Asia/Shanghai --nontp
# System bootloader configuration
bootloader --append="crashkernel=auto" --location=mbr --boot-drive=sda
# Clear the Master Boot Record
zerombr
# Partition clearing information
clearpart --all --initlabel
# Disk partitioning information
part swap --fstype="swap" --ondisk=sda --size=3072
part / --fstype="xfs" --ondisk=sda --size=11200
part /boot --fstype="xfs" --ondisk=sda --size=724
part /data --fstype="xfs" --ondisk=sda --size=3720

%post
useradd wang
%end

%packages
@core
%end

EOF
        fi
	done
if [ "$realeaseNo" -eq "7" -o "$realeaseNo" -eq "8" ];then
cat >/etc/dhcp/dhcpd.conf <<EOF
option domain-name "example.org";
option domain-name-servers 180.76.76.76,114.114.114.114;
default-lease-time 600;
max-lease-time 7200;
log-facility local7;
subnet ${neteth0}.0 netmask 255.255.255.0 {
  range ${neteth0}.100 ${neteth0}.200;
  option routers ${route};
  next-server ${ipeth0};
  filename "pxelinux.0";
}
EOF
fi
if [ "$realeaseNo" -eq "6" ];then
cat >/etc/dhcp/dhcpd.conf <<EOF
option domain-name "example.org";
option domain-name-servers 180.76.76.76,114.114.114.114;
default-lease-time 600;
max-lease-time 7200;
log-facility local7;
subnet ${neteth0}.0 netmask 255.255.255.0 {
  range ${neteth0}.100 ${neteth0}.200;
  option routers ${route6};
  next-server ${ipeth0};
  filename "pxelinux.0";
}
EOF
fi
if [ "$realeaseNo" -eq "7" -o "$realeaseNo" -eq "8" ];then            
	systemctl start dhcpd 
fi 
if [ "$realeaseNo" -eq "6" ];then            
	service dhcpd start 
fi 


\cp /usr/share/syslinux/{pxelinux.0,menu.c32} /var/lib/tftpboot/
\cp /mnt/sr0/isolinux/{ldlinux.c32,libcom32.c32,libutil.c32,vmlinuz,initrd.img} /var/lib/tftpboot/
mkdir /var/lib/tftpboot/pxelinux.cfg/ -p
cat >/var/lib/tftpboot/pxelinux.cfg/default <<EOF
default menu.c32
timeout 600

menu title CentOS Linux 

label linux8
  menu label Auto Install CentOS Linux ^8.0 Mini
  kernel 8/vmlinuz
  append initrd=8/initrd.img ks=http://${ipeth0}/ksdir/ks8.cfg

label linux7
  menu label Auto Install CentOS Linux ^7 Mini
  kernel 7/vmlinuz
  append initrd=7/initrd.img ks=http://${ipeth0}/ksdir/ks7.cfg

label linux6
  menu label Auto Install CentOS Linux ^6 Mini
  kernel 6/vmlinuz
  append initrd=6/initrd.img ks=http://${ipeth0}/ksdir/ks6.cfg

label local
  menu default 
  menu label Boot from ^local drive
  localboot 0xffff
EOF
}

echo "**********************************************************************************************"
echo "***********************************请确保在nat网卡模式下运行***********************************"
echo "**********************************************************************************************"
echo "1..这是一个pxe 自动化安装的脚本；兼容centos6、7、8系统，需要将网卡同一设置为eth0;会自动更改网卡eth0"
echo "2..需要你至少挂载一个光盘；支持cenos6、7、8的光盘"
echo "3..新建虚拟机建议20G 2G内存以上 不然容易报错；"
echo "4..如果运行中有错误请与我联系！谢谢"
echo "5..如果网卡更改后重启了，务必确认是否能ping百度或查看是否有默认网关"
echo "6..如果执行本脚本后发现没有挂载光盘，请执行 yum remove dhcp|dhcp-server httpd tftp-server 清理环境"
echo "7..运行脚本需要在当前shell运行，不要开启子shell，否则无法使用自动更改网卡名功能"
echo "**************************************************************************************"
echo "**************************************************************************************"
echo "虚拟机默认密码为123"
j=20
for i in `seq 20`;do
        echo "${j}s后自动开始运行"
        let j--
        sleep 1
done
PXEinstall
